### ISSUE TITLE
Incorrect wireless card key type

### ISSUE THREAD

**Issue by storyaddict** [system76/tech-docs#119]
Wireless card replacement section identifies the M.2 Slot as A-key, when it should be E-key.

**Comment by jacobgkau** [comment]
Just to be clear, this would not be a typo, this would be incorrect information. Every laptop model's wireless card section says A key, so if this one's wrong, they're probably all wrong.

**Comment by ilikenwf** [comment]
Incorrect for serw13 - I just made a duplicate-ish more specific issue for it.

**Comment by jacobgkau** [comment]
Table of some known key types:

![image](https://github.com/system76/tech-docs/assets/7199422/39e9fbc3-0497-40c2-9ed8-d98b6731fe69)

Per the image below, the key is a requirement that the slot places on the card. In this example, an A+E card fits into an E-only slot, but an A-only card would not fit into an E-only slot.

![image](https://github.com/system76/tech-docs/assets/7199422/486088e7-420f-42da-9342-d5710b816e41)

**Comment by jacobgkau** [comment]
The AX200NGW shown in the serw12 section is A+E, but the slot is E-only:

![image](https://github.com/system76/tech-docs/assets/7199422/2acd637e-983a-452f-b993-a9789152a284)

**Comment by jacobgkau** [comment]
None of our Thelio sections include WiFi card replacement (I think because that requires removal of the motherboard from the chassis for those boards where it's possible), so this issue doesn't affect them.

The meer6's slot is also E-only:

![image](https://github.com/system76/tech-docs/assets/7199422/0786d18d-ae5f-4110-b307-e1a2c342eae8)

The meer5's wireless chip was not M.2-socketed, so it's not affected by this issue:

![image](https://github.com/system76/tech-docs/assets/7199422/e09be330-9325-452e-b772-6e4490f9c72f)

**Comment by jacobgkau** [comment]
Confirmed the recent Pangolins separately since they use a different manufacturer:

![image](https://github.com/system76/tech-docs/assets/7199422/a5c3e60a-f91e-4e06-8e1e-042a9b450c86)

Counting the pins confirms this slot is also E-only, with the card being A+E.
