### ISSUE TITLE
lemp9: LCD panel information

### ISSUE THREAD

**Issue by leviport** [system76/tech-docs#6]
Having basic info about the LCD panel, such as size, resolution, etc. seems helpful. Going even further and including the make and model of the panel would be even better.

At some point, having instructions for replacing the LCD panel would be fantastic. Shipping machines back for repairs isn't always an option for all users, and many are handy enough to perform such a repair themselves.

**Comment by the-vampiire** [comment]
@leviport do you happen to know the screen ' part number of the lemp9?

**Comment by leviport** [comment]
@the-vampiire Sorry for the delayed response. The lemp9 panel is an Innolux N140HCA-EAC

Thank you for the reminder, I really need to get around to adding this!

**Comment by the-vampiire** [comment]
@leviport brilliant thank you. couldnt find this anywhere

**Comment by the-vampiire** [comment]
here is a [link to a supplier](https://www.laptopscreen.com/English/screen-part-number/N140HCA-EAC~REV.C1/) (have not used them before).

now i just need to figure out how to replace it. when i sent it to s76 they took 2 weeks just to diagnose the issue and said there was an unknown time frame for repair!

i cant see any screws or gaps to separate it from the shell. @leviport have you found a guide or have any ideas?

**Comment by leviport** [comment]
It's a pretty difficult procedure, which is why we don't recommend most users try it themselves, but both the LCD bezel and the LCD panel itself are held in with adhesive. I have not done it myself, but I believe a lot of careful peeling should get both the bezel and the panel out. The adhesives may need to be replaced, depending on their condition after all of that peeling. I don't have brand names or part numbers for those adhesive strips either. Thickness is important, so just try to find a sturdy double-stick adhesive of roughly the same thickness. Oh, and be careful of all the cables behind the panel when peeling it out, as they are small and delicate.

**Comment by the-vampiire** [comment]
hey thanks for the honest answer man. maybe i can find someone local to do it professionally. i didnt have a problem with the cost from s76 but the communication and time was unacceptable. from when i sent it out to when i got it back was nearly 4 weeks - and that was without even getting it repaired!

**Comment by leviport** [comment]
> from when i sent it out to when i got it back was nearly 4 weeks - and that was without even getting it repaired!

As a former member of the System76 support team, I can say that such a long wait is uncharacteristic, and this last year has been a bit hectic, to say the least. They're in a much better position to handle repair requests quickly these days. I do understand wanting to get it fixed as quickly as possible though, so no hard feelings if you do get it repaired locally.

**Comment by the-vampiire** [comment]
unfortunately this happened last month (i just received my machine back about 10 days ago). i was patient and understanding of the current circumstances. however the issue seemed to be with disconnect between the support and tech/repair teams. it would take 1-2 days to get responses which is what dragged things out. in the end they did offer to send it back with same day shipping due to how long the process had taken but that was after i called them directly and explained the situation. i had to use a shitty loaner during that time and i was dying to get my machine back! 

its a tough spot. i love what s76 does and recommended their machines to many of my friends. overall i love the lemur pro but the case is just too weak to offer any protection. my support experience was very poor overall and i cant in good faith recommend them going forward because of it. hopefully as they mature they can look into more resilient cases. i would love an aluminum or at least aluminum backed lemp

**Comment by jacobgkau** [comment]
I'm sorry to hear about that experience, but I'm glad the support team was able to hook you up with a loaner machine during the diagnosis, and we're always happy to provide part numbers for local repairs when possible. The support team should have also provided that part number if you'd asked them for it.

This issue will be closed by #86.

**Comment by the-vampiire** [comment]
thanks man, for the record the loaner was from my company. I didn't ask (I thought it might be rude to do so) but I'm glad you guys are adding it to your docs for future reference. 

Hopefully I can find someone local. I can't afford to lose my machine again for several more weeks by having s76 do the repair. My faith would be restored if the internal logistics were evaluated and improved but for now it's a no-go. If anyone internal wants to review my case to see the timeline it's #59295.

**Comment by the-vampiire** [comment]
Originally the issue was related to screen tearing / horizontal lines (original pics at the bottom of the thread). But when they received the machine they told me it was accidental screen damage. When I received the machine back I agreed with their assessment because the entire top left corner is dead. Not blaming anyone there nor did I want to argue about it because it would just be finger pointing. 

To be fair it was "fixed" in that the lines no longer appeared lol just the dead corner that I can work around. 

https://9089701563e3e5947b90-b6e63eb6c42eb9f70edaf30ab1589b06.ssl.cf2.rackcdn.com/bde11584-1047166-8ffdb3706d412c88.jpg
