### ISSUE TITLE
Add links to manuals for older models if they exist

### ISSUE THREAD

**Issue by joemcl** [system76/tech-docs#92]
Please add links to manuals for older models if they exist to https://tech-docs.system76.com/ .

**Comment by leviport** [comment]
Older models are linked from the support documents page: https://support.system76.com/articles/guides

We didn't want to duplicate the functionality of that page, so we're only adding new models to tech-docs.

**Comment by joemcl** [comment]
OK at least link the two pages though :) ? Also, is there not an actual service manual for the Oryx Pro models before model 5 - the [Oryx Pro 1 link](https://support.system76.com/images/guides/orxp1.pdf) there is to a very basic graphic of the outside connectors etc. Or is the model 5 essentially the same as the model 1, just newer hardware? Thanks!

**Comment by ahoneybun** [comment]
@joemcl Thank you for your reported issue! The tech-docs project and the older service manuals were created later on after the Oryx Pro 1 was released. This was caused by our teams and company growing and we're always trying to improve our documentation where ever possible. Currently our available service manuals and tech-docs are here:

https://support.system76.com/articles/guides

and some older models that we have the quickstart guides for are also there as well like the one that you linked to for the Oryx Pro 1. If you have any additional questions about taking the system apart please do reach out to support as we can provide lab photos and assistance there.

**Comment by joemcl** [comment]
Thanks @ahoneybun and I filed a [support request](https://system76.com/my-account/ticket/63595) .
